// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package nodepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NodeClient is the client API for Node service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeClient interface {
	PrepareAndAcknowledge(ctx context.Context, opts ...grpc.CallOption) (Node_PrepareAndAcknowledgeClient, error)
}

type nodeClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeClient(cc grpc.ClientConnInterface) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) PrepareAndAcknowledge(ctx context.Context, opts ...grpc.CallOption) (Node_PrepareAndAcknowledgeClient, error) {
	stream, err := c.cc.NewStream(ctx, &Node_ServiceDesc.Streams[0], "/node.Node/PrepareAndAcknowledge", opts...)
	if err != nil {
		return nil, err
	}
	x := &nodePrepareAndAcknowledgeClient{stream}
	return x, nil
}

type Node_PrepareAndAcknowledgeClient interface {
	Send(*PeerMessage) error
	Recv() (*PeerMessage, error)
	grpc.ClientStream
}

type nodePrepareAndAcknowledgeClient struct {
	grpc.ClientStream
}

func (x *nodePrepareAndAcknowledgeClient) Send(m *PeerMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *nodePrepareAndAcknowledgeClient) Recv() (*PeerMessage, error) {
	m := new(PeerMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NodeServer is the server API for Node service.
// All implementations must embed UnimplementedNodeServer
// for forward compatibility
type NodeServer interface {
	PrepareAndAcknowledge(Node_PrepareAndAcknowledgeServer) error
	mustEmbedUnimplementedNodeServer()
}

// UnimplementedNodeServer must be embedded to have forward compatible implementations.
type UnimplementedNodeServer struct {
}

func (UnimplementedNodeServer) PrepareAndAcknowledge(Node_PrepareAndAcknowledgeServer) error {
	return status.Errorf(codes.Unimplemented, "method PrepareAndAcknowledge not implemented")
}
func (UnimplementedNodeServer) mustEmbedUnimplementedNodeServer() {}

// UnsafeNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServer will
// result in compilation errors.
type UnsafeNodeServer interface {
	mustEmbedUnimplementedNodeServer()
}

func RegisterNodeServer(s grpc.ServiceRegistrar, srv NodeServer) {
	s.RegisterService(&Node_ServiceDesc, srv)
}

func _Node_PrepareAndAcknowledge_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeServer).PrepareAndAcknowledge(&nodePrepareAndAcknowledgeServer{stream})
}

type Node_PrepareAndAcknowledgeServer interface {
	Send(*PeerMessage) error
	Recv() (*PeerMessage, error)
	grpc.ServerStream
}

type nodePrepareAndAcknowledgeServer struct {
	grpc.ServerStream
}

func (x *nodePrepareAndAcknowledgeServer) Send(m *PeerMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *nodePrepareAndAcknowledgeServer) Recv() (*PeerMessage, error) {
	m := new(PeerMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Node_ServiceDesc is the grpc.ServiceDesc for Node service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Node_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "node.Node",
	HandlerType: (*NodeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrepareAndAcknowledge",
			Handler:       _Node_PrepareAndAcknowledge_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "nodepb/node.proto",
}
